name: Test devcontainer
on:
  push:
    branches: "main"
    paths-ignore:
      - CHANGELOG.md
      - CODEOWNERS
      - CONTRIBUTING.md
      - LICENSE
      - README.md
      - tsconfig.json
      - ts
  pull_request:
    branches:
      - '**'
jobs:
  test-devcontainer:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
      - run: deno lint || true
      - run: deno test -A
